---
title: "Report"
output:
  pdf_document: default
  word_document: default
date: "2023-10-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r include=FALSE}
library(lfe)
library(ggplot2)
library(readr)
library(glue)
library(modelsummary)

setwd("E:/social-media-influence-analysis/src/Data")
get_model <- function(model_tbl, reverse) {
  # if we don't reverse, then we are using demand to predict supply
  # so if reverse is FALSE, then we use demands as independent variables
  if(!reverse) {
    model <- felm (supply ~ demand + demand_lag_1 + demand_lag_2 + demand_lag_3 + demand_lag_4 | time_window + bin, data = model_tbl)
  } else {
    model <- felm (demand ~ supply + supply_lag_1 + supply_lag_2 + supply_lag_3 + supply_lag_4 |  time_window + bin, data = model_tbl)
  }
  return(model)
}

get_model_past <- function(model_tbl, reverse) {
  # if we don't reverse, then we are using demand to predict supply
  # so if reverse is FALSE, then we use demands as independent variables
  if(!reverse) {
    model <- felm (supply ~ demand_lag_1 + demand_lag_2 + demand_lag_3 + demand_lag_4 |  time_window + bin, data = model_tbl)
  } else {
    model <- felm (demand ~ supply_lag_1 + supply_lag_2 + supply_lag_3 + supply_lag_4 |  time_window + bin, data = model_tbl)
  }
  return(model)
}

draw_graphs <- function(model_tbl_fitted, reverse, result) {
  if(!reverse) {
    combined_plot <- ggplot(model_tbl_fitted, aes(x = time_window)) +
    geom_line(aes(y = core_node_supply, color = "Core Node Supply"), linetype = "solid") +
    geom_line(aes(y = fitted, color = "Prediction"), linetype = "solid") +
    facet_wrap(~bin) +
    labs(title = "Core Node Supply and Predicted Supply vs Time Window",
         x = "Time Window",
         y = "Value") +
    theme_minimal()
  
    # Save the combined plot
    ggsave(file = glue('ml_1_single_core_node/combined.png'), plot = combined_plot)
  } else {
    # Assuming your data frame is named your_data
    combined_plot <- ggplot(model_tbl_fitted, aes(x = time_window)) +
    geom_line(aes(y = supply, color = "Demand"), linetype = "solid") +
    geom_line(aes(y = fitted, color = "Prediction"), linetype = "solid") +
    facet_wrap(~bin) +
    labs(title = "Demand and Predicted Demand vs Time Window",
         x = "Time Window",
         y = "Value") +
    theme_minimal()
    
    ggsave(file = glue('{result}_one_chess/combined_reversed.png'), plot = combined_plot)
  }
}


draw_both <- function(numbers, reverse) {
  result <- paste(numbers, collapse = "_")
  file_path <- glue("{result}_cns/{result}_cns.csv")
  model_tbl <- read_csv(file_path)
  
  model <- get_model(model_tbl, reverse)

  model_tbl_fitted <- model_tbl

  model_tbl_fitted$fitted <- model$fitted.values

  # draw_graphs(model_tbl_fitted, reverse, result)
  
  return(model)
}

```

```{r include=FALSE}
m_9 <- draw_both(c(9), FALSE)
m_11 <- draw_both(c(11), FALSE)
summary_table_for_1 <- modelsummary(models = list(m_9, m_11), output = "latex", stats = TRUE, fmt=4, statistic = c("std.error"), coef_omit = "^topic")
```

```{r include=FALSE }
m_6_9 <- draw_both(c(6, 9), FALSE)
m_11_13 <- draw_both(c(11, 13), FALSE)
m_9_13 <- draw_both(c(9, 13), FALSE)
m_13_15 <- draw_both(c(13,15), FALSE)
m_13_17 <- draw_both(c(13, 17), FALSE)
m_15_17 <- draw_both(c(15, 17), FALSE)
```

``` {r}
summary_table_for_2 <- modelsummary(models = list( m_11_13, m_9_13, m_13_15, m_13_17), output="latex", 
           stars = TRUE, fmt = 4, statistic = c("std.error"), 
            coef_omit = "^topic")
summary_table_for_2
```

``` {r}
m_6_9 <- draw_both(c(6, 9), TRUE)
m_11_13 <- draw_both(c(11, 13), TRUE)
m_9_13 <- draw_both(c(9, 13), TRUE)
m_13_15 <- draw_both(c(13,15), TRUE)
m_13_17 <- draw_both(c(13, 17), TRUE)
m_15_17 <- draw_both(c(15, 17), TRUE)
```

``` {r}
summary_table_for_2_inverted <- modelsummary(models = list(m_6_9, m_11_13, m_9_13, m_13_15, m_13_17, m_15_17), output="latex", 
           stars = TRUE, fmt = 4, statistic = c("std.error"), 
            coef_omit = "^topic")
summary_table_for_2_inverted
```

``` {r}
m_6_9_11 <- draw_both(c(6, 9, 11), FALSE)
m_9_11_13 <- draw_both(c(9, 11, 13), FALSE)
m_11_13_15 <- draw_both(c(11, 13, 15), FALSE)
m_13_15_17 <- draw_both(c(13, 15, 17), FALSE)
```
``` {r}
summary_table_for_3 <- modelsummary(models = list(m_6_9_11, m_9_11_13, m_11_13_15, m_13_15_17), output="latex", 
           stars = TRUE, fmt = 4, statistic = c("std.error"), 
            coef_omit = "^topic")
summary_table_for_3
```

``` {r}
m_6_9_11 <- draw_both(c(6, 9, 11), TRUE)
m_9_11_13 <- draw_both(c(9, 11, 13), TRUE)
m_11_13_15 <- draw_both(c(11, 13, 15), TRUE)
m_13_15_17 <- draw_both(c(13, 15, 17), TRUE)
```
``` {r}
summary_table_for_3_inverted <- modelsummary(models = list(m_6_9_11, m_9_11_13, m_11_13_15, m_13_15_17), output="latex", 
           stars = TRUE, fmt = 4, statistic = c("std.error"), 
            coef_omit = "^topic")
summary_table_for_3_inverted
```






```{r}
m_12_14_16_18 <- draw_both(c(12, 14, 16, 18), FALSE)
m_2_3_4_5 <- draw_both(c(2,3,4,5), FALSE)
m_3_6_9_12 <- draw_both(c(3, 6, 9, 12), FALSE)
m_6_9_11_13 <- draw_both(c(6, 9, 11, 13), FALSE)
m_11_13_15_17 <- draw_both(c(11, 13, 15, 17), FALSE)
summary_table_for_4 <- modelsummary(models = list(m_12_14_16_18, m_3_6_9_12, m_6_9_11_13, m_11_13_15_17), output="latex", 
           stars = TRUE, fmt = 4, statistic = c("std.error"), 
            coef_omit = "^topic")
summary_table_for_4
```


```{r}
m_12_14_16_18 <- draw_both(c(12, 14, 16, 18), TRUE)
m_2_3_4_5 <- draw_both(c(2,3,4,5), TRUE)
m_3_6_9_12 <- draw_both(c(3, 6, 9, 12), TRUE)
m_6_9_11_13 <- draw_both(c(6, 9, 11, 13), TRUE)
m_11_13_15_17 <- draw_both(c(11, 13, 15, 17), TRUE)
summary_table_for_4 <- modelsummary(models = list(m_12_14_16_18, m_2_3_4_5, m_3_6_9_12, m_6_9_11_13, m_11_13_15_17), output="latex", 
           stars = TRUE, fmt = 4, statistic = c("std.error"), 
            coef_omit = "^topic")
summary_table_for_4
```

```{r}
  file <- "13_15_17_cns"
  file_path <- glue("{file}/{file}.csv")
  model_tbl <- read_csv(file_path)
  results <- list()
  
  model <- felm (supply ~ demand | time_window + bin, data = model_tbl)
  results <- c(results, coef(summary(model))[4])
  
  model <- felm (supply ~ demand_lag_1 | time_window + bin, data = model_tbl)
  results <- c(results, coef(summary(model))[4])
  
  model <- felm (supply ~ demand_lag_2 | time_window + bin, data = model_tbl)
  results <- c(results, coef(summary(model))[4])
  
  model <- felm (supply ~ demand_lag_3 | time_window + bin, data = model_tbl)
  results <- c(results, coef(summary(model))[4])
  
  model <- felm (supply ~ demand_lag_4 | time_window + bin, data = model_tbl)
  results <- c(results, coef(summary(model))[4])
  
  model <- felm (supply ~ demand_lag_5 | time_window + bin, data = model_tbl)
  results <- c(results, coef(summary(model))[4])
  
  model <- felm (supply ~ demand_lag_6 | time_window + bin, data = model_tbl)
  results <- c(results, coef(summary(model))[4])
  
  model <- felm (supply ~ demand_lag_7 | time_window + bin, data = model_tbl)
  results <- c(results, coef(summary(model))[4])
  
  
  ########################################################
  nresults <- list()
  model <- felm (demand ~ supply | time_window + bin, data = model_tbl)
  nresults <- c(nresults, coef(summary(model))[4])
  
  model <- felm (demand ~ supply_lag_1 | time_window + bin, data = model_tbl)
  nresults <- c(nresults, coef(summary(model))[4])
  
  model <- felm (demand ~ supply_lag_2 | time_window + bin, data = model_tbl)
  nresults <- c(nresults, coef(summary(model))[4])

  model <- felm (demand ~ supply_lag_3 | time_window + bin, data = model_tbl)
  nresults <- c(nresults, coef(summary(model))[4])
  
  model <- felm (demand ~ supply_lag_4 | time_window + bin, data = model_tbl)
  nresults <- c(nresults, coef(summary(model))[4])
  
  model <- felm (demand ~ supply_lag_5 | time_window + bin, data = model_tbl)
  nresults <- c(nresults, coef(summary(model))[4])
  
  model <- felm (demand ~ supply_lag_6 | time_window + bin, data = model_tbl)
  nresults <- c(nresults, coef(summary(model))[4])
  
  model <- felm (demand ~ supply_lag_7 | time_window + bin, data = model_tbl)
  nresults <- c(nresults, coef(summary(model))[4])
  
  data <- data.frame(
    x = c(0, 1, 2, 3, 4, 5, 6, 7 ),
    positive = unlist(results),
    negative = unlist(nresults)
  )

  
    combined_plot <- ggplot(data, aes(x = x)) +
  geom_line(aes(y = positive, color="positive"), linetype = "solid", color = "blue") +
  geom_line(aes(y = negative, color="negative"), linetype = "solid", color = "red") +
  labs(title = "p-value trends",
       x = "lag",
       y = "p-Value") +
  theme_minimal()+ 
 annotate(
    "text",
    x = Inf, y = Inf,
    label = "Blue: Positive, Red: Negative",
    hjust = 1, vjust = 1,
    size = 4,
    color = "black"
  )
    
    combined_plot
  
  ggsave(file = glue('{file}/p_trend.png'), plot = combined_plot)
```



```{r}
  file <- "11_13_15_17_cns"
  file_path <- glue("{file}/{file}.csv")
  model_tbl <- read_csv(file_path)
  
  
  model <- felm (supply ~ demand | time_window + bin, data = model_tbl)
  print(model$pval)
  model <- felm (supply ~ demand + demand_lag_1| time_window + bin, data = model_tbl)
  print(model$pval)
  model <- felm (supply ~ demand + demand_lag_1 + demand_lag_2| time_window + bin, data = model_tbl)
  print(model$pval)
  model <- felm (supply ~ demand + demand_lag_1 + demand_lag_2 + demand_lag_3| time_window + bin, data = model_tbl)
  print(model$pval)
  model <- felm (supply ~ demand + demand_lag_1 + demand_lag_2 + demand_lag_3 + demand_lag_4| time_window + bin, data = model_tbl)
  print(model$pval)
  model <- felm (supply ~ demand + demand_lag_1 + demand_lag_2 + demand_lag_3 + demand_lag_4 + demand_lag_5| time_window + bin, data = model_tbl)
  print(model$pval)
  model <- felm (supply ~ demand + demand_lag_1 + demand_lag_2 + demand_lag_3 + demand_lag_4 + demand_lag_5 + demand_lag_6| time_window + bin, data = model_tbl)
  print(model$pval)
  model <- felm (supply ~ demand + demand_lag_1 + demand_lag_2 + demand_lag_3 + demand_lag_4 + demand_lag_5 + demand_lag_6 + demand_lag_7| time_window + bin, data = model_tbl)
  print(model$pval)

```


```{r}

# P-values for different lags and variables
p_values <- c(
  1.246805e-18, NA, NA, NA, NA, NA, NA, NA,
  8.220184e-18, 1.390632e-01, NA, NA, NA, NA, NA, NA,
  1.726298e-17, 1.615241e-01, 4.857248e-01, NA, NA, NA, NA, NA,
  8.076976e-17, 2.254747e-01, 6.451610e-01, 1.484407e-02, NA, NA, NA, NA,
  1.239533e-16, 2.971917e-01, 7.801028e-01, 2.757481e-02, 1.538258e-02, NA, NA, NA,
  1.855154e-16, 3.069884e-01, 8.242516e-01, 3.271701e-02, 1.974749e-02, 3.826342e-01, NA, NA,
  2.415688e-16, 3.124892e-01, 8.283182e-01, 3.435645e-02, 2.104274e-02, 3.974287e-01, 8.034805e-01, NA,
  1.387890e-16, 2.745849e-01, 7.861524e-01, 3.226292e-02, 1.672569e-02, 3.430190e-01, 7.048256e-01, 1.406432e-01
)

# Reshape the data into a matrix
p_values_matrix <- matrix(p_values, nrow = 8, byrow = TRUE)

# Convert the matrix into a data frame
p_values_df <- as.data.frame(p_values_matrix)

# Adding column and row names
colnames(p_values_df) <- c("lag_0", "lag_1", "lag_2", "lag_3", "lag_4", "lag_5", "lag_6", "lag_7")
rownames(p_values_df) <- c(1, 2, 3, 4, 5, 6, 7, 8)


# Printing the data frame
print(p_values_df)


```
